[full]

    [full.nmap-full-tcp]

        [full.nmap-full-tcp.service-detection]
        command = 'nmap {nmap_extra} -A -T4 --osscan-guess --version-all -p- --min-rate=1000 -oN "{scandir}/_full_tcp_nmap.txt" -oX "{scandir}/xml/_full_tcp_nmap.xml" {target_address}'

    [full.nmap-top-20-udp]

        [full.nmap-top-20-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -A -T4 --top-ports=20 --version-all --min-rate=1000 -oN "{scandir}/_top_20_udp_nmap.txt" -oX "{scandir}/xml/_top_20_udp_nmap.xml" {target_address}'

    [full.nmap-vulns]

        [full.nmap-vulns.service-detection]
        command = 'nmap {nmap_extra} -T4 --script=*vuln* --min-rate=1000 -oN "{scandir}/_vulns_nmap.txt" -oX "{scandir}/xml/_vulns_nmap.xml" {target_address}'

[quick]

    [quick.nmap-quick]

        [quick.nmap-quick.service-detection]
        command = 'nmap {nmap_extra} -sV --version-all -oN "{scandir}/_quick_tcp_nmap.txt" -oX "{scandir}/xml/_quick_tcp_nmap.xml" {target_address}'

    [quick.nmap-top-20-udp]

        [quick.nmap-top-20-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -A --top-ports=20 --version-all -oN "{scandir}/_top_20_udp_nmap.txt" -oX "{scandir}/xml/_top_20_udp_nmap.xml" {target_address}'

[udp]

    [udp.udp-top-20]

        [udp.udp-top-20.port-scan]
        command = 'unicornscan -mU -p 631,161,137,123,138,1434,445,135,67,53,139,500,68,520,1900,4500,514,49152,162,69 {target_address} 2>&1 | tee "{scandir}/_top_20_udp_unicornscan.txt"'

        [udp.udp-top-20.service-detection]
        command = 'nmap {nmap_extra} -sU -A -p {ports} --version-all -oN "{scandir}/_top_20_udp_nmap.txt" -oX "{scandir}/xml/_top_20_udp_nmap.xml" {target_address}'
